// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RdzzxYtXNDmXwthAFULht
// Component: H9F5a25JrzZP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: dwt2e_8l2G6M/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 3RdzzxYtXNDmXwthAFULht/projectcss
import sty from "./PlasmicLogout.module.css"; // plasmic-import: H9F5a25JrzZP/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 5E-obxmHF72A/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: _rPDvpvkM_d8/icon

createPlasmicElementProxy;

export type PlasmicLogout__VariantMembers = {};
export type PlasmicLogout__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogout__VariantsArgs;
export const PlasmicLogout__VariantProps = new Array<VariantPropType>();

export type PlasmicLogout__ArgsType = {};
type ArgPropType = keyof PlasmicLogout__ArgsType;
export const PlasmicLogout__ArgProps = new Array<ArgPropType>();

export type PlasmicLogout__OverridesType = {
  root?: Flex__<"div">;
  logOut?: Flex__<typeof Button>;
};

export interface DefaultLogoutProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogout__RenderFunc(props: {
  variants: PlasmicLogout__VariantsArgs;
  args: PlasmicLogout__ArgsType;
  overrides: PlasmicLogout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        data-plasmic-name={"logOut"}
        data-plasmic-override={overrides.logOut}
        className={classNames("__wab_instance", sty.logOut)}
      >
        {"Log out"}
      </Button>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "logOut"],
  logOut: ["logOut"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  logOut: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogout__VariantsArgs;
    args?: PlasmicLogout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLogout__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLogout__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogout__ArgProps,
          internalVariantPropNames: PlasmicLogout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogout";
  } else {
    func.displayName = `PlasmicLogout.${nodeName}`;
  }
  return func;
}

export const PlasmicLogout = Object.assign(
  // Top-level PlasmicLogout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logOut: makeNodeComponent("logOut"),

    // Metadata about props expected for PlasmicLogout
    internalVariantProps: PlasmicLogout__VariantProps,
    internalArgProps: PlasmicLogout__ArgProps
  }
);

export default PlasmicLogout;
/* prettier-ignore-end */
