// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLogout,
  DefaultLogoutProps
} from "./plasmic/proliga/PlasmicLogout";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import {createPagesBrowserClient} from "@supabase/auth-helpers-nextjs";
import {useRouter} from "next/router";
import {PLASMIC_AUTH_DATA_KEY} from "../utils/cache-keys";
import {mutate} from "swr";


export interface LogoutProps extends DefaultLogoutProps {}

function Logout_(props: LogoutProps, ref: HTMLElementRefOf<"div">) {
  const [supabaseClient] = React.useState(() => createPagesBrowserClient());
  const router = useRouter();

  return <PlasmicLogout root={{ ref }} {...props}
                        submitButton={{
                          onClick: async () => {
                            await supabaseClient.auth.signOut();
                            await mutate(PLASMIC_AUTH_DATA_KEY);
                            // router.reload();
                            router.push('/login')
                          },
                        }}/>;
}

const Logout = React.forwardRef(Logout_);
export default Logout;
