// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
    PlasmicRegister,
    DefaultRegisterProps
} from "./plasmic/proliga/PlasmicRegister";
import {HTMLElementRefOf} from "@plasmicapp/react-web";
import {useState} from "react";
import {createPagesBrowserClient} from "@supabase/auth-helpers-nextjs";
import {useRouter} from "next/router";
import {mutate} from "swr";
import {PLASMIC_AUTH_DATA_KEY} from "../utils/cache-keys";


export interface RegisterProps extends DefaultRegisterProps {
}

function Register_(props: RegisterProps, ref: HTMLElementRefOf<"div">) {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [supabaseClient] = React.useState(() => createPagesBrowserClient());
    const router = useRouter();
    return <PlasmicRegister root={{ref}} {...props}

                            emailInput={{
                                value: email,
                                onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
                                    setEmail(e.target.value);
                                }
                            }
                            }
                            passwordInput={{
                                value: password,
                                onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
                                    setPassword(e.target.value);
                                }
                            }}
                            submitButton={{
                                onClick: async () => {
                                    const {data, error} = await supabaseClient.auth.signUp({
                                        email: email,
                                        password: password
                                    });

                                    if (error){
                                        console.error(error)
                                        alert(error)
                                    }
                                    else {
                                        // alert(password)
                                        router.push("/");
                                        await mutate(PLASMIC_AUTH_DATA_KEY);}

                                }

                            }

                            }/>;
}

const Register = React.forwardRef(Register_);
export default Register;
